name: Deploy nsjail to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
      push-store-image:
        permissions:
          contents: read
          packages: write
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build . --tag ghcr.io/gcc-ensibs/docker-nsjail:latest
              docker push ghcr.io/gcc-ensibs/docker-nsjail:latest